OUTNAME_RELEASE = sample_onnx_mnist_cn
OUTNAME_DEBUG   = sample_onnx_mnist_cn_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
