# Compile options
DEBUG                       :=  0
SHOW_WARNING                :=  0

# Compile applications
APP				            :=  trt-infer
## You can also choose otherapplications. Currently, we support following applications:
## 1. trt-infer
## 2. trt-tracker
