#Update the install directory paths for dependencies below
CXX                         :=  g++
CUDA_VER                    :=  11.7

#Set to TEGRA for jetson or TESLA for dGPU's
PLATFORM                    :=  TESLA

#For Tesla Plugins
OPENCV_INSTALL_DIR          :=  /usr/local/include/opencv4
TENSORRT_INSTALL_DIR        :=  /home/kalfazed/packages/TensorRT-8.5.1.7
DEEPSTREAM_INSTALL_DIR      :=  /path/to/DeepStream_Release_3.0

#For Tegra Plugins
NVGSTIVA_APP_INSTALL_DIR    :=  /path/to/nvgstiva-app_sources

# Compile options
DEBUG                       :=  1
SHOW_WARNING                :=  0

# Compile applications
APP				            :=  trt-infer
## You can also choose otherapplications. Currently, we support following applications:
## 1. trt-infer
## 2. trt-tracker
