# Compile options
DEBUG                       :=  1
SHOW_WARNING                :=  0

# Compile applications
APP                         :=  trt-infer
## You can also choose otherapplications. Currently, we support following applications:
## 1. trt-cuda
## 2. trt-infer
## 3. trt-tracker
